feat: add variables for beta releases
gravity-ui/release-action pull request #1
Opened 2023-03-29 17:15 UTC by yuberdysheva

2023-04-06 11:03 UTC, amje requested changes

2023-04-06 11:03 UTC, amje commented on action.yml
> +  - run: npm publish ${{ inputs.npm-dist-tag }} --access public
Suggestion: `npm publish --tag ${{ inputs.npm-dist-tag }}` and set default to `latest`

2023-04-06 12:04 UTC, amje requested changes

2023-04-06 12:04 UTC, amje commented on action.yml
> +    default: '--latest'
Let it be just `latest` w/o `--`

2023-04-06 15:43 UTC, julebird commented
I've tested the last changes in the project `@gravity-ui/page-constructor` and released alpha-version 2.2.2-alpha.4
https://github.com/gravity-ui/page-constructor/actions/runs/4630174843

2023-04-07 15:41 UTC, amje approved these changes

2023-04-11 11:29 UTC, merged